version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Подключаем volume для статики
      - db_volume:/app/db
    expose:
      - "8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "promptProject.wsgi:application"]

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles  # Используем ту же папку
    ports:
      - "8089:80"

volumes:
  static_volume:
  db_volume:
