# Generated by Django 5.1.6 on 2025-02-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_design", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="prompt_text",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="response_text",
        ),
        migrations.AddField(
            model_name="prompt",
            name="developer_content",
            field=models.TextField(
                blank=True, help_text="Системное сообщение для API", null=True
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="max_tokens",
            field=models.PositiveIntegerField(
                default=1000, help_text="Максимальное количество токенов"
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="temperature",
            field=models.FloatField(
                default=0.0, help_text="Температура генерации (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="user_content",
            field=models.TextField(
                blank=True, help_text="Контент от пользователя", null=True
            ),
        ),
    ]
