# Generated by Django 5.1.6 on 2025-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_design", "0004_alter_prompt_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "GPT-4o"),
                    ("o1", "o1"),
                    ("o3-mini", "o3-mini"),
                    ("gpt-4", "GPT-4"),
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("grok-beta", "grok-beta"),
                    ("grok-2-1212", "grok-2"),
                ],
                default="gpt-4o",
                help_text="Выберите модель API",
                max_length=20,
            ),
        ),
    ]
